const cacheName = 'ready-set-school-v6-single-session';
const appFiles = ['./', './index.html', './styles.css', './app.js', './manifest.json', './icon-192.svg', './icon-512.svg'];

self.addEventListener('install', (event) => {
  self.skipWaiting();
  event.waitUntil(caches.open(cacheName).then((cache) => cache.addAll(appFiles)));
});

self.addEventListener('push', (event) => {
  let data = {};
  try { data = event.data?.json() || {}; } catch { data = { body: event.data?.text() || '' }; }

  const title = data.title || 'Ready Set School';
  const options = {
    body: data.body || 'You have a school reminder.',
    icon: './icon-192.svg',
    badge: './icon-192.svg',
    tag: data.tag || 'ready-set-school-reminder',
    data: { url: data.url || './' }
  };

  event.waitUntil(self.registration.showNotification(title, options));
});create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  username text not null,
  name text not null,
  photo text,
  items jsonb not null default '[]'::jsonb,
  schedule_url text,
  schedule_image text,
  notifications jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null,
  subscription jsonb not null,
  created_at timestamptz not null default now(),
  unique (user_id, endpoint)
);

create table if not exists public.sent_reminders (
  user_id uuid not null references auth.users(id) on delete cascade,
  item_id text not null,
  reminder_date date not null,
  reminder_time time not null,
  primary key (user_id, item_id, reminder_date, reminder_time)
);import webpush from 'npm:web-push@3.6.7';

const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
const serviceRoleKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const vapidSubject = Deno.env.get('VAPID_SUBJECT')!;
const vapidPublicKey = Deno.env.get('VAPID_PUBLIC_KEY')!;
const vapidPrivateKey = Deno.env.get('VAPID_PRIVATE_KEY')!;

webpush.setVapidDetails(vapidSubject, vapidPublicKey, vapidPrivateKey);

Deno.serve(async () => {
  const now = new Date();
  const profiles = await supabaseRequest('profiles?select=id,items');
  let sent = 0;

  for (const profile of profiles || []) {
    const subscriptions = await supabaseRequest(`push_subscriptions?user_id=eq.${profile.id}&select=endpoint,subscription`);
    for (const subscription of subscriptions || []) {
      for (const item of profile.items || []) {
        if (!item.reminderTime || item.reminderTime > currentTime || !(item.reminderDays || []).includes(day)) continue;
        try {
          await webpush.sendNotification(subscription.subscription, JSON.stringify({
            title: 'Ready Set School',
            body: `Remember: ${item.name}`
          }));
          sent += 1;
        } catch (error) {
          // delete stale push subscription if needed
        }
      }
    }
  }

  return new Response(JSON.stringify({ sent }), { headers: { 'Content-Type': 'application/json' } });
});
